[tool.poetry]
name = "benchmark"
version = "0.1.0"
description = ""
authors = ["Daniel Carl Jones <djonesoa@amazon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
hydra-core = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
