version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"
- package-ecosystem: 'cargo'
  directory: '/'
  schedule:
    interval: 'daily'
    time: "00:00"
- package-ecosystem: 'cargo'
  directory: '/mountpoint-s3-crt/'
  schedule:
    interval: 'daily'
    time: "00:00"
