name: Integration Tests

# We use environments to require approval to run integration tests on PRs, but not on pushes to
# `main` (which have been approved already since PRs are required for `main`).
on:
  workflow_call:
    inputs:
      environment:
        type: string
      ref:
        required: true
        type: string

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  S3_BUCKET_TEST_PREFIX: ${{ vars.S3_BUCKET_TEST_PREFIX || 'github-actions-tmp/' }}run-${{ github.run_id }}/attempt-${{ github.run_attempt }}/
  RUST_FEATURES: fuse_tests,s3_tests,checksum
  # Defaults if not overridden by jobs.
  S3_BUCKET_NAME: ${{ fromJSON(vars.S3_TARGETS).testTargets[0].bucket }}
  # A bucket our IAM role has no access to, but is in the right region, for permissions tests
  S3_FORBIDDEN_BUCKET_NAME: ${{ fromJSON(vars.S3_TARGETS).testTargets[0].forbiddenBucket }}
  S3_REGION: ${{ fromJSON(vars.S3_TARGETS).testTargets[0].region }}
  IAM_ROLE: ${{ fromJSON(vars.S3_TARGETS).testTargets[0].role }}

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: ${{ matrix.testTarget.region}}; FUSE ${{matrix.fuseVersion}}; ${{matrix.runner.name}}
    runs-on: ${{ matrix.runner.tags }}

    environment: ${{ inputs.environment }}

    strategy:
      matrix:
        runner:
        - name: Ubuntu x86
          tags: [ubuntu-22.04] # GitHub-hosted
        - name: AL2 ARMv8
          tags: [self-hosted, linux, arm64]
        fuseVersion: [2, 3]
        testTarget: ${{ fromJSON(vars.S3_TARGETS).testTargets }}
        exclude:
        - fuseVersion: 3
          runner:
          - name: AL2 ARMv8
    env:
      S3_BUCKET_NAME: ${{ matrix.testTarget.bucket }}
      # A bucket our IAM role has no access to, but is in the right region, for permissions tests
      S3_FORBIDDEN_BUCKET_NAME: ${{ matrix.testTarget.forbiddenBucket }}
      S3_REGION: ${{ matrix.testTarget.region }}
      IAM_ROLE: ${{ matrix.testTarget.role }}

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.IAM_ROLE }}
        aws-region: ${{ env.S3_REGION }}
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        submodules: true
        persist-credentials: false
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Restore Cargo cache
      id: restore-cargo-cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ github.job }}-integration-${{ matrix.fuse }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install and configure FUSE
      uses: ./.github/actions/configure-fuse
      with:
        fuseVersion: ${{ matrix.fuseVersion }}
    - name: Build tests
      run: cargo test --features $RUST_FEATURES --no-run
    - name: Run tests
      run: cargo test --features $RUST_FEATURES
    - name: Save Cargo cache
      uses: actions/cache/save@v3
      if: inputs.environment != 'PR integration tests'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ steps.restore-cargo-cache.outputs.cache-primary-key }}

  asan:
    name: Address sanitizer
    runs-on: ubuntu-22.04

    environment: ${{ inputs.environment }}

    timeout-minutes: 60

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.IAM_ROLE }}
        aws-region: ${{ env.S3_REGION }}
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rust-src
    - name: Restore Cargo cache
      id: restore-cargo-cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ github.job }}-integration-asan-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install llvm-dev
      run: sudo apt-get install llvm-dev
    - name: Install and configure FUSE
      uses: ./.github/actions/configure-fuse
      with:
        fuseVersion: 3
    - name: Validate ASan is working
      run: make test-asan-working
    - name: Run tests
      run: make test-asan
    - name: Save Cargo cache
      uses: actions/cache/save@v3
      if: inputs.environment != 'PR integration tests'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ steps.restore-cargo-cache.outputs.cache-primary-key }}
